### ISSUE TITLE
Sign up for more volunteers at freecodecamp

### ISSUE THREAD

**Issue by thejameslang** [rare-genomics/rg-mobile#15]
https://docs.google.com/forms/d/1MtQDh8E1Nvkg5jdOucS4LSyk6oMQrN8XTwmQGtgJPAQ/viewform?embedded=true

**Comment by dianeoliveira** [comment]
Sent the filled form to them. 
They will reply back if we got selected.

**Comment by BeatrizJones** [comment]
Diane,

Please Sign me in for the freecode camp.


Thank you

Beatriz
