### ISSUE TITLE
Screen 3.3 - Medication Alert Settings

### ISSUE THREAD

**Issue by dianeoliveira** [rare-genomics/rg-mobile#40]
No UC. See Wireframe on Balsamiq

**Comment by dianeoliveira** [comment]
Need to review this screens. Maybe we don't need it because this function is content in 3.2 (Medication and Alarm together)

**Comment by rsc2015** [comment]
@dianeoliveira we can review the functionality of the medication detail screens.

**Comment by dianeoliveira** [comment]
We will need to have a meeting and take the final decision because we have other difference there. I sent the invite for tomorrow at 4 pm EST.

**Comment by rsc2015** [comment]
This screen is not required since the medication alarm setting is already in 3.0 medication intake tracker screen.

**Comment by dianeoliveira** [comment]
Moving Screens to Done, once no work is necessary here.
